---
test_name: Hivemind database_api.list_comments patterns test order "by_last_update" author with blank category posts

marks:
  - patterntest # fat node didn't limit results to replies to posts of given author

includes:
  - !include ../../../common.yaml

stages:
  - name: list_comments_by_update
    request:
      url: "{service.proto:s}://{service.server:s}:{service.port}/"
      method: POST
      headers:
        content-type: application/json
      json:
        jsonrpc: "2.0"
        id: 1
        method: "database_api.list_comments"
        params:
          {
            "start": ["xeroc", "2016-04-14T14:55:27", "", ""],
            "limit": 10,
            "order": "by_last_update",
          }
    response:
      status_code: 200
      verify_response_with:
        function: validate_response:compare_response_with_pattern
        extra_kwargs:
          method: "blank_category"
          directory: "database_api_patterns/list_comments/by_last_update"

