---
test_name: Hivemind database_api.list_comments patterns test order "by_cashout_time" all data

marks:
  - patterntest # fat node didn't like that format of date (so original made with regular ISO format date)
                # also results incomparable with original due to differences in cashout (pattern the same as in author_permlink)

includes:
  - !include ../../../common.yaml

stages:
  - name: list_comments_by_cashout_time
    request:
      url: "{service.proto:s}://{service.server:s}:{service.port}/"
      method: POST
      headers:
        $ext:
            function: validate_response:get_headers
      json:
        jsonrpc: "2.0"
        id: 1
        method: "database_api.list_comments"
        params:
          {
            "start":["2016-01-08 01:01:01","",""],
            "limit": 10,
            "order": "by_cashout_time",
          }
    response:
      status_code: 200
      verify_response_with:
        function: validate_response:compare_response_with_pattern
        extra_kwargs:
          method: "date"
          directory: "database_api_patterns/list_comments/by_cashout_time"
