---
test_name: Hivemind database_api.list_comments patterns test order "by_author_last_update" correct date author and permlink

marks:
  - patterntest # fat node did not require author account
  - negative

includes:
  - !include ../../../common.yaml

stages:
  - name: list_comments_by_author_last_update
    request:
      url: "{service.proto:s}://{service.server:s}:{service.port}/"
      method: POST
      headers:
        $ext:
            function: validate_response:get_headers
      json:
        jsonrpc: "2.0"
        id: 1
        method: "database_api.list_comments"
        params:
          {
            "start": ["", "2016-08-28T17:15:12", "givemeyoursteem", "winners-of-steemit-food-challenge-3-desserts-to-die-for"],
            "limit": 10,
            "order": "by_author_last_update",
          }
    response:
      status_code: 200
      verify_response_with:
        function: validate_response:compare_response_with_pattern
        extra_kwargs:
          method: "no_author"
          directory: "database_api_negative/list_comments/by_author_last_update"
          error_response: true
