stages:
  - build
  - test
  - publish
  - cleanup

variables:
  GIT_DEPTH: 20
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: "recursive"
  CI_DEBUG_SERVICES: "true"
  # uses registry.gitlab.syncad.com/hive/haf/ci-base-image:ubuntu22.04-5
  BUILDER_IMAGE_TAG: "@sha256:2da00c8f151d9d582c21c99b24b988e58138a6bf682516a5a8bd740af0b24c89"

  # references registry.gitlab.syncad.com/hive/hive/ci-base-image:ubuntu22.04-6
  PYTEST_RUNTIME_IMAGE_NAME: "registry.gitlab.syncad.com/hive/hive/ci-base-image@sha256:8132802ca3b7ddba1bf78e4cc5ce1fbda6874cb029e35ae855c4cb3443e477b7"
  POETRY_INSTALL_ROOT_DIR: "${CI_PROJECT_DIR}/haf/hive/tests/hive-local-tools"

  SETUP_SCRIPTS_PATH: "$CI_PROJECT_DIR/haf/scripts"
  REGISTRY: registry.gitlab.syncad.com/hive/hafah
  APP_PORT: 6543
  HAF_POSTGRES_URL: postgresql://haf_app_admin@haf-instance:5432/haf_block_log
  BENCHMARK_SOURCE_DIR: "$CI_PROJECT_DIR/haf/hive/tests/hive-local-tools/tests_api/benchmarks"

  # Variables required by Common CI jobs
  TOX_IMAGE_TAG: "4b62d20dfebebacf51ca8795f3d7c4df2d9b8565"
  BUILDER_IMAGE_PATH: "registry.gitlab.syncad.com/hive/haf/ci-base-image${BUILDER_IMAGE_TAG}"

  # Variables specific to runner (there is single runner cache and there is 5m block_log available)
  DATA_CACHE_HIVE_TEMPLATE: /cache/replay_data_hafah_hived
  DATA_CACHE_HAF_TEMPLATE: /cache/replay_data_hafah_haf
  DATA_CACHE_HIVE: "/cache/replay_data_hafah_hive_${CI_PIPELINE_ID}"
  DATA_CACHE_HAF: "/cache/replay_data_hafah_haf_${CI_PIPELINE_ID}"
  BLOCK_LOG_SOURCE_DIR_5M: /blockchain/block_log_5m

include:
  - template: Workflows/Branch-Pipelines.gitlab-ci.yml
  - project: 'hive/haf'
    ref: 365b6663b6ebc0cd00fe01f822a02ed16c294df5 # develop
    file: '/scripts/ci-helpers/prepare_data_image_job.yml'
  - project: 'hive/common-ci-configuration'
    ref: 4b62d20dfebebacf51ca8795f3d7c4df2d9b8565 # bw_reusing_pattern_tests_template_defs # It seems a variable cannot be used here
    file: '/templates/test_jobs.gitlab-ci.yml'

prepare_hived_image:
  extends: .prepare_hived_image
  stage: build
  variables:
    SUBMODULE_DIR: "$CI_PROJECT_DIR/haf/hive"
    REGISTRY_USER: "$HIVED_CI_IMGBUILDER_USER"
    REGISTRY_PASS: $HIVED_CI_IMGBUILDER_PASSWORD
  tags:
    - public-runner-docker
    - hived-for-tests

prepare_hived_data:
  extends: .prepare_hived_data_5m
  needs:
    - job: prepare_hived_image
      artifacts: true
  stage: build
  variables:
    SUBMODULE_DIR: "$CI_PROJECT_DIR/haf/hive"
    BLOCK_LOG_SOURCE_DIR: $BLOCK_LOG_SOURCE_DIR_5M
    CONFIG_INI_SOURCE: "$CI_PROJECT_DIR/haf/hive/docker/config_5M.ini"
  resource_group: ${CI_COMMIT_SHA}
  tags:
    - data-cache-storage

prepare_haf_image:
  extends: .prepare_haf_image
  stage: build
  variables:
    SUBMODULE_DIR: "$CI_PROJECT_DIR/haf"
    REGISTRY_USER: "$CI_IMG_BUILDER_USER"
    REGISTRY_PASS: $CI_IMG_BUILDER_PASSWORD
  tags:
    - public-runner-docker
    - hived-for-tests

prepare_haf_data:
  extends: .prepare_haf_data_5m
  needs:
    - job: prepare_haf_image
      artifacts: true
  stage: build
  variables:
    SUBMODULE_DIR: "$CI_PROJECT_DIR/haf"
    BLOCK_LOG_SOURCE_DIR: $BLOCK_LOG_SOURCE_DIR_5M
    CONFIG_INI_SOURCE: "$CI_PROJECT_DIR/haf/docker/config_5M.ini"
  resource_group: ${CI_COMMIT_SHA}
  tags:
    - data-cache-storage

.prepare_hafah_image:
  extends: .docker_image_builder_job
  stage: build
  variables:
    HAFAH_IMAGE_TAG: ""
    HAFAH_IMAGE_NAME: $CI_REGISTRY_IMAGE/instance:instance-$HAFAH_IMAGE_TAG
    USE_POSTGREST: 0
    SOURCE_DIR: $CI_PROJECT_DIR

  script:
    - echo $HAFAH_IMAGE_NAME
    - echo $SOURCE_DIR
    - |
      scripts/ci-helpers/build_instance.sh
      docker login -u "$HAFAH_CI_IMG_BUILDER_USER" -p "$HAFAH_CI_IMG_BUILDER_PASSWORD" "$REGISTRY"
      docker push "$HAFAH_IMAGE_NAME"
      echo "HAFAH_IMAGE_NAME=$HAFAH_IMAGE_NAME" > docker_image_name.env

  artifacts:
    reports:
      dotenv: docker_image_name.env
    expire_in: 6 hours

  tags:
    - public-runner-docker
    - hived-for-tests

prepare_postgrest_hafah_image:
  extends: .prepare_hafah_image
  variables:
    HAFAH_IMAGE_TAG: postgrest-$CI_COMMIT_SHORT_SHA
    USE_POSTGREST: 1

.pattern_tests:
  extends: .haf_app_pattern_tests_template 
  stage: test
  variables:
    HAF_APP_IMAGE: ""
    HAF_APP_PORT: ${APP_PORT}

    PYTEST_BASED_IMAGE_NAME: ${PYTEST_RUNTIME_IMAGE_NAME}
    POETRY_INSTALL_ROOT_DIR: "${CI_PROJECT_DIR}/haf/hive/tests/hive-local-tools"

    PYTHONPATH: "$CI_PROJECT_DIR/haf/hive/tests/hive-local-tools/test-tools/package"

    TEST_SUITE: "condenser_api_patterns/get_transaction and not get_transaction_hex or account_history_api or condenser_api_patterns/get_account_history or condenser_api_patterns/get_ops_in_block"
    PATTERN_TESTS_DIR: "${CI_PROJECT_DIR}/haf/hive/tests/api_tests/pattern_tests"
    JUNIT_REPORT: "haf/hive/tests/api_tests/pattern_tests/results.xml"
    DIRECT_CALLS: 0
    HIVED_UID: $HIVED_UID

  needs:
    - job: prepare_haf_data
      artifacts: true

  before_script:
    - !reference [.haf_app_pattern_tests_template, before_script]
    - echo "HAfAH image name $HAF_APP_IMAGE"
    - echo "HAF image name $HAF_IMAGE_NAME"

  artifacts:
    paths:
    - "$CI_JOB_NAME"
    - "**/from_node.log"
    - "**/ah.log"
    - "**/*.out.json"
    - "tests/tests_api/hived/workdir_*"
    - "haf/hive/tests/api_tests/pattern_tests/results.xml"

  resource_group: ${CI_COMMIT_SHA}
  tags:
    - data-cache-storage

postgrest_pattern_tests:
  extends: .pattern_tests

  needs:
    - !reference [.pattern_tests, needs]
    - job: prepare_postgrest_hafah_image
      artifacts: true

  variables:
    HAF_APP_IMAGE: $HAFAH_IMAGE_NAME

new_style_postgrest_pattern_tests:
  extends: .pattern_tests

  needs:
    - !reference [.pattern_tests, needs]
    - job: prepare_postgrest_hafah_image
      artifacts: true

  variables:
    HAF_APP_IMAGE: $HAFAH_IMAGE_NAME
    # Direct call version does not support condenser_api
    TEST_SUITE: "account_history_api"
    DIRECT_CALLS: 1

.comparison_tests:
  extends: .comparison_tests_template
  stage: test
  variables:
    PYTEST_BASED_IMAGE_NAME: ${PYTEST_RUNTIME_IMAGE_NAME}
    POETRY_INSTALL_ROOT_DIR: "${CI_PROJECT_DIR}/haf/hive/tests/hive-local-tools"
    COMPARISON_TESTS_DIR: "$CI_PROJECT_DIR/haf/hive/tests/api_tests/comparsion_tests"
    HAF_APP_PORT: ${APP_PORT}
    HIVED_UID: $HIVED_UID

  needs:
    - job: prepare_haf_data
      artifacts: true
    - job: prepare_hived_data
      artifacts: true

  artifacts:
    paths:
      - "$CI_JOB_NAME"
      - "**/from_node.log"
      - "**/ah.log"
      - "**/*.out.json"

    reports:
      junit: "haf/hive/tests/api_tests/comparsion_tests/comparsion_tests.xml"

  resource_group: ${CI_COMMIT_SHA}
  tags:
    - data-cache-storage

postgrest_comparison_tests:
  extends: .comparison_tests

  needs:
    - !reference [.comparison_tests, needs]
    - job: prepare_postgrest_hafah_image
      artifacts: true

  variables:
    HAF_APP_IMAGE: $HAFAH_IMAGE_NAME

.benchmark_tests:
  extends: .jmeter_benchmark_with_haf_job
  stage: test
  variables:
    FF_NETWORK_PER_BUILD: 1
    API_FOR_TESTING: "account_history_api" # alternatively: blocks_api
    PYTHONPATH: "$CI_PROJECT_DIR/haf/hive/tests/hive-local-tools/test-tools/package"
    APP_IMAGE: ""
    HIVED_UID: $HIVED_UID
  needs:
    - job: prepare_haf_data
      artifacts: true

  script:
      - /usr/bin/python3 "${BENCHMARK_SOURCE_DIR}/benchmark.py" -a app -p $APP_PORT -c perf_5M_heavy.csv -d $CI_PROJECT_DIR/wdir -n $API_FOR_TESTING
      - m2u --input wdir/raw_jmeter_report.xml --output wdir/jmeter_junit_report.xml
      - jmeter -g wdir/jmeter_${APP_PORT}_output.csv -o wdir/dashboard/
  artifacts:
    paths:
      - wdir/
    reports:
      junit: wdir/jmeter_junit_report.xml
  resource_group: ${CI_COMMIT_SHA}
  tags:
    - data-cache-storage

postgrest_block_api_benchmark_tests:
  extends: .benchmark_tests

  needs:
    - !reference [.benchmark_tests, needs]
    - job: prepare_postgrest_hafah_image
      artifacts: true

  variables:
    APP_IMAGE: $HAFAH_IMAGE_NAME
    API_FOR_TESTING: blocks_api

postgrest_account_history_benchmark_tests:
  extends: .benchmark_tests

  needs:
    - !reference [.benchmark_tests, needs]
    - job: prepare_postgrest_hafah_image
      artifacts: true

  variables:
    APP_IMAGE: $HAFAH_IMAGE_NAME

cleanup_hived_cache_manual:
  extends: .cleanup_cache_manual
  stage: cleanup
  variables:
    CLEANUP_PATH_PATTERN: "/cache/replay_data_hafah_*"
  resource_group: ${CI_COMMIT_SHA}
  tags:
    - data-cache-storage

build_and_publish_image:
  stage: publish
  extends: .publish_docker_image_template
  script:
    - scripts/ci-helpers/build_and_publish_instance.sh
  tags:
    - public-runner-docker

prepare_haf_image_testnet:
  extends: .prepare_haf_image
  stage: build
  variables:
    SUBMODULE_DIR: "$CI_PROJECT_DIR/haf"
    REGISTRY_USER: "$CI_IMG_BUILDER_USER"
    REGISTRY_PASS: $CI_IMG_BUILDER_PASSWORD
    HIVE_NETWORK_TYPE: testnet
    BINARY_CACHE_PATH: "haf-testnet-binaries"
  tags:
    - public-runner-docker
    - hived-for-tests

.hfm-only-service: &hfm-only-service
  name: $HAF_IMAGE_NAME
  alias: hfm-only-instance
  variables:
    # Allow access from any network to eliminate CI IP addressing problems when hfm runs as service
    PG_ACCESS: |
                "host    all              haf_admin        0.0.0.0/0    trust"
                "host    all              haf_app_admin    0.0.0.0/0    trust"
                "host    all              all              0.0.0.0/0    scram-sha-256"
  command: ["--execute-maintenance-script=/home/haf_admin/haf/scripts/maintenance-scripts/sleep_infinity.sh"]

.hafah_pytest_fuctional_tests_base:
  stage: test
  extends: .pattern_tests
  needs:
    - job: prepare_haf_image_testnet
      artifacts: true
    - job: prepare_postgrest_hafah_image
      artifacts: true
  image: $BUILDER_IMAGE_PATH
  services:
    - *hfm-only-service
    - name: $APP_IMAGE
      alias: app
  variables:
    BINARY_CACHE_PATH: "haf-testnet-binaries"
    HIVED_PATH: "$CI_PROJECT_DIR/$BINARY_CACHE_PATH/hived"
    COMPRESS_BLOCK_LOG_PATH: "$CI_PROJECT_DIR/$BINARY_CACHE_PATH/compress_block_log"
    GET_DEV_KEY_PATH: "$CI_PROJECT_DIR/$BINARY_CACHE_PATH/get_dev_key"
    CLI_WALLET_PATH: "$CI_PROJECT_DIR/$BINARY_CACHE_PATH/cli_wallet"
    DB_NAME: haf_block_log
    DB_URL: "postgresql://haf_admin@hfm-only-instance:5432/$DB_NAME"
    APP_IMAGE: $HAFAH_IMAGE_NAME
    POSTGRES_URL: $DB_URL
  script:
      # - export PATH="/home/haf_admin/.local/bin:$PATH"
    - curl -sSL https://install.python-poetry.org | python3 -  # install poetry in isolated environment
    - python3 -m venv venv/
    - . venv/bin/activate
    - (cd $CI_PROJECT_DIR/tests/integration/hafah-local-tools && poetry install)

    # setup postgres and DB for work with hafah
    - $CI_PROJECT_DIR/scripts/setup_postgres.sh --postgres-url="$DB_URL"
    - bash ${CI_PROJECT_DIR}/scripts/generate_version_sql.bash ${CI_PROJECT_DIR}
    - $CI_PROJECT_DIR/scripts/setup_db.sh --postgres-url="$DB_URL"

    # run tests
    - cd $CI_PROJECT_DIR/tests/integration/functional
    - pytest --junitxml report.xml --postgrest-hafah-adress=app:$APP_PORT --postgres-db-url=$DB_URL -m $PYTEST_MARK
  artifacts:
    paths:
    - "**/generated_during_*"
    - "**/generated_by_package_fixtures"
    reports:
      junit: tests/integration/system/haf/report.xml
    when: always
    expire_in: 1 week
  interruptible: true
  resource_group:
  tags:
    - hived-for-tests

hafah_pytest_fuctional_tests_part1:
  extends: .hafah_pytest_fuctional_tests_base
  variables:
    PYTEST_MARK: "enum_virtual_ops_and_get_ops_in_block"

hafah_pytest_fuctional_tests_part2:
  extends: .hafah_pytest_fuctional_tests_base
  variables:
    PYTEST_MARK: "get_account_history_and_get_transaction"
