stages:
  - build_and_test

variables:
  GIT_DEPTH: "1"
  GIT_SUBMODULE_STRATEGY: "recursive"
  BUILDER_IMAGE_TAG: "@sha256:c299b6f2d0928adbf02bd40158cd8acd0b32187686b97e88303182ba82d12647"

hive_fork_manager:
  stage: build_and_test
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  script:
    - /etc/init.d/postgresql start
    - mkdir -p "$CI_JOB_NAME"/build
    - cd "$CI_JOB_NAME"/build
    - cmake -DCMAKE_BUILD_TYPE=Release -DHIVE_LINT=ON ../../haf
    - make extension.hive_fork_manager -j10
    - make install
    - ctest --output-on-failure  -R test.functional.hive_fork_manager.*
  artifacts:
    paths:
    - "$CI_JOB_NAME"
    expire_in: 6 hours
  tags:
    - public-runner-docker

hived:
  stage: build_and_test
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  script:
    - /etc/init.d/postgresql start
    - mkdir -p "$CI_JOB_NAME"/build
    - cd "$CI_JOB_NAME"/build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCLEAR_VOTES=ON -DENABLE_MIRA=OFF -DBUILD_HIVE_TESTNET=OFF -DHIVE_LINT=ON ../../haf
    - make hived truncate_block_log -j10
    # check if sql_serializer compiles with hived
    - test -f hive/libraries/plugins/sql_serializer/libsql_serializer_plugin.a
    # check if sql_serializer plugin is included in hived plugins
    - cd ./hive/programs/hived
    - ./hived --help | grep psql-url
  artifacts:
    paths:
    - "$CI_JOB_NAME"
    expire_in: 6 hours
  tags:
    - public-runner-docker

patterns_tests:
  stage: build_and_test
  needs:
    - job: hive_fork_manager
      artifacts: true
    - job: hived
      artifacts: true
  image: "$CI_REGISTRY_IMAGE/builder$BUILDER_IMAGE_TAG"
  variables:
    HIVE_BUILD_ROOT_PATH: "$CI_PROJECT_DIR/hived/build/hive"
    EXTENSION_BUILD_ROOT_PATH: "$CI_PROJECT_DIR/hive_fork_manager/build"
    BLOCK_LOG_PATH: "/blockchain/block_log"
  script:
    - apt-get install tox -y
    - pip3 install -r requirements.txt

    # install extension build in previous stage
    # replay and prepare database
    - if [ ! "$POSTGRESQL_URI" ] && [ ! "$AH_ENDPOINT" ]; then
        /etc/init.d/postgresql start ;
        cd $EXTENSION_BUILD_ROOT_PATH ;
        make install ;
        psql -d postgres -c 'CREATE DATABASE haf_block_log' ;
        psql -d haf_block_log -c 'CREATE EXTENSION hive_fork_manager CASCADE' ;
        mkdir $CI_PROJECT_DIR/tests/patterns/.hived/blockchain ;
        $HIVE_BUILD_ROOT_PATH/programs/util/truncate_block_log $BLOCK_LOG_PATH $CI_PROJECT_DIR/tests/patterns/.hived/blockchain/block_log 5000000 ;
        $HIVE_BUILD_ROOT_PATH/programs/hived/hived --data-dir $CI_PROJECT_DIR/tests/patterns/.hived --config config.ini --force-replay --exit-before-sync > $CI_PROJECT_DIR/from_node.log 2>&1 ;
        export POSTGRESQL_URI='postgresql:///haf_block_log' ;
      fi

    # run account history
    - if [ ! "$AH_ENDPOINT" ]; then
        cd $CI_PROJECT_DIR ;
        ./main.py --psql-db-path $POSTGRESQL_URI --port 6543 &
        export AH_ENDPOINT=http://localhost:6543 ;
      fi

    # run tests
    - cd $CI_PROJECT_DIR/tests/patterns
    - echo $POSTGRESQL_URI
    - echo $AH_ENDPOINT
    - tox

  artifacts:
    paths:
    - "$CI_JOB_NAME"
    - "**/from_node.log"
    - "**/ah.log"
    - "**/*.out.json"
    when: always
    expire_in: 6 hours
  tags:
    - public-runner-docker
    - hived-for-tests
