stages:
  - build
  - test

variables:
  GIT_DEPTH: "1"
  GIT_SUBMODULE_STRATEGY: "recursive"
  # uses registry.gitlab.syncad.com/hive/haf/ci-base-image:ubuntu20.04-5
  BUILDER_IMAGE_TAG: "@sha256:6b557af6a98188c118d442b68437bf1b20d67e3aae5765269c4fe88465c62d60"
  SETUP_SCRIPTS_PATH: "$CI_PROJECT_DIR/haf/scripts"
  REGISTRY: registry.gitlab.syncad.com/hive/hafah
  HAFAH_PORT: 6543
  HAF_POSTGRES_URL: postgresql://haf_app_admin@haf-instance:5432/haf_block_log
  CACHED_BENCHMARK_DIR: "$CI_PROJECT_DIR/cached"

include:
  - project: 'hive/haf'
    ref: develop
    file: '/scripts/ci-helpers/prepare_data_image_job.yml'

  - project: 'hive/hive'
    ref: develop
    file: '/scripts/ci-helpers/prepare_data_image_job.yml'

prepare_haf_image:
  extends: .prepare_haf_data_5m_image
  stage: build
  variables:
    SUBMODULE_DIR: "$CI_PROJECT_DIR/haf"
    REGISTRY_USER: "$CI_IMG_BUILDER_USER"
    REGISTRY_PASS: $CI_IMG_BUILDER_PASSWORD

  tags:
    - public-runner-docker
    - hived-for-tests


.prepare_hafah_image:
  extends: .docker_image_builder_job
  stage: build
  variables:
    HAFAH_IMAGE_NAME: ""
    USE_POSTGREST: 0

  script:
    - cat /etc/docker/daemon.json
    - docker info
    - docker network ls
    - docker network inspect $(docker network ls -q)
    - docker build --build-arg USE_POSTGREST=$USE_POSTGREST --build-arg HTTP_PORT=$HAFAH_PORT --build-arg POSTGRES_URL="$HAF_POSTGRES_URL" --target=instance -t $HAFAH_IMAGE_NAME -f Dockerfile .
    - echo $HAFAH_CI_IMG_BUILDER_PASSWORD | docker login -u $HAFAH_CI_IMG_BUILDER_USER $REGISTRY --password-stdin
    - docker push $HAFAH_IMAGE_NAME
    - echo "HAFAH_IMAGE_NAME=$HAFAH_IMAGE_NAME" > docker_image_name.env

  artifacts:
    reports:
      dotenv: docker_image_name.env
    expire_in: 6 hours

  tags:
    - public-runner-docker
    - hived-for-tests

prepare_python_hafah_image:
  extends: .prepare_hafah_image
  variables:
    HAFAH_IMAGE_NAME: $REGISTRY/python-instance:$CI_COMMIT_SHORT_SHA
    USE_POSTGREST: 0

.patterns_tests:
  stage: test
  variables:
    AH_ENDPOINT: hafah_app:$HAFAH_PORT
    FF_NETWORK_PER_BUILD: 1
    PYTHONPATH: "$CI_PROJECT_DIR/haf/hive/tests/test_tools/package"
    HAFAH_IMAGE: ""
    DOCKER_BUILDKIT: 1
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: "/certs"
  image: docker:20.10.10

  needs:
    - job: prepare_haf_image
      artifacts: true

  services:
    - docker:20.10.10-dind

    - name: $HAF_IMAGE_NAME
      alias: haf-instance

#    - name: $HAFAH_IMAGE
#      alias: hafah_app

  before_script:
    - cat /etc/docker/daemon.json
    - echo "HAfAH image name $HAFAH_IMAGE"
    - echo "HAF image name $HAF_IMAGE_NAME"
    - docker info
    - docker network ls
    - docker network inspect $(docker network ls -q)
    - docker container ls
    - docker container inspect haf-instance
    - docker container inspect hafah_app

  script:
    - docker info
    - docker network ls
    - docker network inspect $(docker network ls -q)
    - docker container ls
    - docker container inspect haf-instance
    - docker container inspect hafah_app

  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/haf/hive/tests/api_tests/pattern_tests/results.xml
    paths:
    - "$CI_JOB_NAME"
    - "**/from_node.log"
    - "**/ah.log"
    - "**/*.out.json"
    - "$CI_PROJECT_DIR/haf/hive/tests/tests_api/hived/workdir_*"
    when: always
    expire_in: 6 hours
  tags:
    - public-runner-docker
    - hived-for-tests

python_patterns_tests:
  extends: .patterns_tests

 # needs:
 #   - !reference [.patterns_tests, needs]
 #   - job: prepare_python_hafah_image
 #     artifacts: true

  variables:
    HAFAH_IMAGE: $HAFAH_IMAGE_NAME
