stages:
  - build_and_test

variables:
  GIT_DEPTH: "1"
  GIT_SUBMODULE_STRATEGY: "recursive"
  # uses registry.gitlab.syncad.com/hive/haf/ci-base-image:ubuntu20.04-3
  BUILDER_IMAGE_TAG: "@sha256:a701abca3cdd31bc3a5c7e58a8a2a9ea752e7f30e100aa41bcfe9c56b777883f"
  SETUP_SCRIPTS_PATH: "$CI_PROJECT_DIR/haf/scripts"

include:
  - project: 'hive/haf'
    ref: develop
    file: '/scripts/ci-helpers/prepare_data_image_job.yml'

prepare_haf_image:
  extends: .prepare_haf_data_5m_image
  stage: build_and_test
  artifacts:
    paths:
      - haf_docked_image.txt
    expire_in: 6 hours

  tags:
    - public-runner-docker
    - hived-for-tests

prepare_hafah_image:
  extends: .docker_image_builder_job
  stage: build_and_test
  script:
  -  docker build --target=HafAH -t registry.gitlab.syncad.com/hive/hafah/hafah:$CI_COMMIT_SHORT_SHA -f Dockerfile . 
  tags:
    - public-runner-docker
    - hived-for-tests

patterns_tests:
  extends: .docker_image_builder_job
  stage: build_and_test

  needs:
    - job: prepare_haf_image
      artifacts: true
    - job: prepare_hafah_image

  script:
    - cat haf_docked_image.txt

    # run HAfAH
    - if [ ! "$AH_ENDPOINT" ]; then
        cd $CI_PROJECT_DIR ;
        ./main.py --psql-db-path $POSTGRESQL_URI --port 6543 >> ah.log &
        export AH_ENDPOINT=localhost:6543 ;
      fi

    # run pattern tests
    - cd $CI_PROJECT_DIR/haf/hive/tests/api_tests
    - ./run_tests.sh $AH_ENDPOINT `git rev-parse --show-toplevel`

    # run comparsion tests
    - export AHRB_PORT=$(cat $CI_PROJECT_DIR/tests/prepare_database/config.ini | grep webserver-http-endpoint | cut -d ':' -f 2)
    - export TJOBS=10
    - cd $CI_PROJECT_DIR/haf/hive/tests/tests_api/hived
    - ./test_ah_enum_virtual_ops.py --ref http://localhost:$AHRB_PORT --test http://$AH_ENDPOINT --start 4900000 --stop 4925000 -d workdir_enum -j $TJOBS
    - ./test_ah_get_ops_in_block.py --ref http://localhost:$AHRB_PORT --test http://$AH_ENDPOINT --start 4900000 --stop 4925000 -d workdir_ops -j $TJOBS
    - ./test_ah_get_account_history.py --ref http://localhost:$AHRB_PORT --test http://$AH_ENDPOINT -f ./input_data/accounts.csv -d workdir_acc -j $TJOBS
    - ./test_ah_get_transaction.py --ref http://localhost:$AHRB_PORT --test http://$AH_ENDPOINT -f ./input_data/hashes.csv -d workdir_trx -j $TJOBS

    # kill hived
    - pkill hived

  artifacts:
    when: always
    reports:
      junit: $CI_PROJECT_DIR/haf/hive/tests/api_tests/results.xml
    paths:
    - "$CI_JOB_NAME"
    - "**/from_node.log"
    - "**/ah.log"
    - "**/*.out.json"
    - "$CI_PROJECT_DIR/haf/hive/tests/tests_api/hived/workdir_*"
    when: always
    expire_in: 6 hours
  tags:
    - public-runner-docker
    - hived-for-tests
