stages:
  - build_and_test

variables:
  GIT_DEPTH: "1"
  GIT_SUBMODULE_STRATEGY: "recursive"
  # uses registry.gitlab.syncad.com/hive/haf/ci-base-image:ubuntu20.04-5 
  BUILDER_IMAGE_TAG: "@sha256:a22b174d15ad9878f878e798e297d2134da132174802abff0923ea214e2f4543"
  SETUP_SCRIPTS_PATH: "$CI_PROJECT_DIR/haf/scripts"

include:
  - project: 'hive/haf'
    ref: develop
    file: '/scripts/ci-helpers/prepare_data_image_job.yml'

prepare_haf_image:
  extends: .prepare_haf_data_5m_image
  stage: build_and_test
  artifacts:
    paths:
      - haf_docked_image.txt
    expire_in: 6 hours

  tags:
    - public-runner-docker
    - hived-for-tests

prepare_hafah_image:
  extends: .docker_image_builder_job
  stage: build_and_test
  script:
  -  docker build --target=HafAH -t registry.gitlab.syncad.com/hive/hafah/hafah:$CI_COMMIT_SHORT_SHA -f Dockerfile . 
  tags:
    - public-runner-docker
    - hived-for-tests

patterns_tests:
  extends: .docker_image_builder_job
  stage: build_and_test

  needs:
    - job: prepare_haf_image
      artifacts: true
    - job: prepare_hafah_image
  image: "$CI_REGISTRY_IMAGE/ci-base-image$BUILDER_IMAGE_TAG"
  variables:
    HIVE_BUILD_ROOT_PATH: "$CI_PROJECT_DIR/hived/build/hive"
    BLOCK_LOG_PATH: "/blockchain/block_log"
    PYTHONPATH: "$CI_PROJECT_DIR/haf/hive/tests/test_tools/package"
  script:
    - pip3 install -r $CI_PROJECT_DIR/haf/hive/tests/api_tests/comparsion_tests/requirements.txt

    # run HAfAH
    - if [ ! "$AH_ENDPOINT" ]; then
        cd $CI_PROJECT_DIR ;
        export DEBUG=1 ;
        ./main.py --psql-db-path $POSTGRESQL_URI --port 6543 2>&1 >> ah.log &
        export AH_ENDPOINT=localhost:6543 ;
      fi

    # run pattern tests
    - cd $CI_PROJECT_DIR/haf/hive/tests/api_tests/pattern_tests
    - ./run_tests.sh $AH_ENDPOINT `git rev-parse --show-toplevel`

    # run comparsion tests
    - export AHRB_PORT=$(cat $CI_PROJECT_DIR/tests/prepare_database/config.ini | grep webserver-http-endpoint | cut -d ':' -f 2)
    - pushd $CI_PROJECT_DIR/haf/hive/tests/api_tests/comparsion_tests
    - python3 -m pytest -n 8 --ref http://localhost:$AHRB_PORT --test http://$AH_ENDPOINT --start 4900000 --stop 4915000 --junitxml=$CI_PROJECT_DIR/comparsion_tests.xml
    - popd

    # kill hived and HAfAH
    - pkill hived
    - pkill main.py

  artifacts:
    when: always
    reports:
      junit:
        - $CI_PROJECT_DIR/comparsion_tests.xml
        - $CI_PROJECT_DIR/haf/hive/tests/api_tests/results.xml
    paths:
    - "$CI_JOB_NAME"
    - "**/from_node.log"
    - "**/ah.log"
    - "**/*.out.json"
    - "$CI_PROJECT_DIR/haf/hive/tests/tests_api/hived/workdir_*"
    when: always
    expire_in: 6 hours
  tags:
    - public-runner-docker
    - hived-for-tests
