stages:
  - build
  - test
  - publish

variables:
  GIT_DEPTH: "1"
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: "recursive"
  # uses registry.gitlab.syncad.com/hive/haf/ci-base-image:ubuntu20.04-5
  BUILDER_IMAGE_TAG: "@sha256:6b557af6a98188c118d442b68437bf1b20d67e3aae5765269c4fe88465c62d60"
  SETUP_SCRIPTS_PATH: "$CI_PROJECT_DIR/haf/scripts"
  REGISTRY: registry.gitlab.syncad.com/hive/hafah
  APP_PORT: 6543
  HAF_POSTGRES_URL: postgresql://haf_app_admin@haf-instance:5432/haf_block_log
  BENCHMARK_SOURCE_DIR: "$CI_PROJECT_DIR/haf/hive/tests/tests_api/benchmarks"

  # Variables required by Common CI jobs
  CI_COMMON_JOB_VERSION: "656cd1670240c01fe05e56ee7158ea04877da555"
  IMAGE_REMOVER_TAG: "$CI_COMMON_JOB_VERSION"
  TOX_IMAGE_TAG: "$CI_COMMON_JOB_VERSION"

include:
  - template: Workflows/Branch-Pipelines.gitlab-ci.yml
  - project: 'hive/haf'
    ref: 9cb65db8cc3e36c8aa9b32b2b9978f7aa22f7de8
    file: '/scripts/ci-helpers/prepare_data_image_job.yml'
  - project: 'hive/hive'
    ref: 6d3c2c0f988c87f9ad69f89e1d9710721f0dca19
    file: '/scripts/ci-helpers/prepare_data_image_job.yml'
  - project: 'hive/common-ci-configuration'
    ref: 656cd1670240c01fe05e56ee7158ea04877da555 # It seems a variable cannot be used here
    file: '/templates/docker_image_jobs.gitlab-ci.yml'
  - project: 'hive/common-ci-configuration'
    ref: 656cd1670240c01fe05e56ee7158ea04877da555 # It seems a variable cannot be used here
    file: '/templates/test_jobs.gitlab-ci.yml'

prepare_hived_image:
  extends: .prepare_hived_data_5m_image
  stage: build
  variables:
    SUBMODULE_DIR: "$CI_PROJECT_DIR/haf/hive"
    REGISTRY_USER: "$HIVED_CI_IMGBUILDER_USER"
    REGISTRY_PASS: $HIVED_CI_IMGBUILDER_PASSWORD
  tags:
    - public-runner-docker
    - hived-for-tests

prepare_haf_image:
  extends: .prepare_haf_data_5m_image
  stage: build
  variables:
    SUBMODULE_DIR: "$CI_PROJECT_DIR/haf"
    REGISTRY_USER: "$CI_IMG_BUILDER_USER"
    REGISTRY_PASS: $CI_IMG_BUILDER_PASSWORD
  tags:
    - public-runner-docker
    - hived-for-tests

.prepare_hafah_image:
  extends: .docker_image_builder_job
  stage: build
  variables:
    HAFAH_IMAGE_NAME: ""
    USE_POSTGREST: 0
    SOURCE_DIR: $CI_PROJECT_DIR

  script:
    - |
      scripts/ci-helpers/build_instance.sh
      docker login -u "$HAFAH_CI_IMG_BUILDER_USER" -p "$HAFAH_CI_IMG_BUILDER_PASSWORD" "$REGISTRY"
      docker push "$HAFAH_IMAGE_NAME"
      echo "HAFAH_IMAGE_NAME=$HAFAH_IMAGE_NAME" > docker_image_name.env

  artifacts:
    reports:
      dotenv: docker_image_name.env
    expire_in: 6 hours

  tags:
    - public-runner-docker
    - hived-for-tests

prepare_python_hafah_image:
  extends: .prepare_hafah_image
  variables:
    HAFAH_IMAGE_NAME: $REGISTRY/python-instance:$CI_COMMIT_SHORT_SHA
    USE_POSTGREST: 0

prepare_postgrest_hafah_image:
  extends: .prepare_hafah_image
  variables:
    HAFAH_IMAGE_NAME: $REGISTRY/postgrest-instance:$CI_COMMIT_SHORT_SHA
    USE_POSTGREST: 1

.pattern_tests:
  extends: .pattern_tests_template
  stage: test
  variables:
    FF_NETWORK_PER_BUILD: 1
    PYTHONPATH: "$CI_PROJECT_DIR/tests/test-tools/package"
    APP_IMAGE: ""
    TEST_SUITE: "condenser_api_patterns/get_transaction and not get_transaction_hex or account_history_api or condenser_api_patterns/get_account_history or condenser_api_patterns/get_ops_in_block"
    DIRECT_HAFAH_CALLS: 0

  needs:
    - job: prepare_haf_image
      artifacts: true

  before_script:
    - echo "HAfAH image name $APP_IMAGE"
    - echo "HAF image name $HAF_IMAGE_NAME"

  script:
    - pip3 install -r $CI_PROJECT_DIR/haf/hive/tests/api_tests/comparsion_tests/requirements.txt
    # run pattern tests
    - cd $CI_PROJECT_DIR/haf/hive/tests/api_tests/pattern_tests
    - ./run_tests.sh $ENDPOINT `git rev-parse --show-toplevel` "${TEST_SUITE}" ${DIRECT_HAFAH_CALLS}

  artifacts:
    paths:
    - "$CI_JOB_NAME"
    - "**/from_node.log"
    - "**/ah.log"
    - "**/*.out.json"
    - "tests/tests_api/hived/workdir_*"
    - "tests/api_tests/pattern_tests/results.xml"
    reports:
      junit: haf/hive/tests/api_tests/pattern_tests/results.xml
  tags:
    - public-runner-docker
    - hived-for-tests

python_pattern_tests:
  extends: .pattern_tests

  needs:
    - !reference [.pattern_tests, needs]
    - job: prepare_python_hafah_image
      artifacts: true

  variables:
    APP_IMAGE: $HAFAH_IMAGE_NAME

postgrest_pattern_tests:
  extends: .pattern_tests

  needs:
    - !reference [.pattern_tests, needs]
    - job: prepare_postgrest_hafah_image
      artifacts: true

  variables:
    APP_IMAGE: $HAFAH_IMAGE_NAME

new_style_postgrest_pattern_tests:
  extends: .pattern_tests

  needs:
    - !reference [.pattern_tests, needs]
    - job: prepare_postgrest_hafah_image
      artifacts: true

  variables:
    APP_IMAGE: $HAFAH_IMAGE_NAME
    # Direct call version does not support condenser_api
    TEST_SUITE: "account_history_api"
    DIRECT_HAFAH_CALLS: 1

.comparison_tests:
  extends: .comparison_tests_template
  stage: test
  variables:
    FF_NETWORK_PER_BUILD: 1
    PYTHONPATH: "$CI_PROJECT_DIR/tests/test-tools/package"

  needs:
    - job: prepare_haf_image
      artifacts: true
    - job: prepare_hived_image
      artifacts: true

  script:
    - pip3 install -r $CI_PROJECT_DIR/haf/hive/tests/api_tests/comparsion_tests/requirements.txt "$CI_PROJECT_DIR/tests/test-tools"
      # run comparsion tests
    - cd $CI_PROJECT_DIR/haf/hive/tests/api_tests/comparsion_tests
    - python3 -m pytest -n 8 --ref http://$HIVED_ENDPOINT --test http://$ENDPOINT --start 4900000 --stop 4915000 --junitxml=$CI_PROJECT_DIR/comparsion_tests.xml

  artifacts:
    paths:
    - "$CI_JOB_NAME"
    - "**/from_node.log"
    - "**/ah.log"
    - "**/*.out.json"
    - "haf/hive/tests/tests_api/hived/workdir_*"
    - "comparsion_tests.xml"
    reports:
      junit:
        - comparsion_tests.xml 
  tags:
    - public-runner-docker
    - hived-for-tests

python_comparison_tests:
  extends: .comparison_tests

  needs:
    - !reference [.comparison_tests, needs]
    - job: prepare_python_hafah_image
      artifacts: true

  variables:
    APP_IMAGE: $HAFAH_IMAGE_NAME

postgrest_comparison_tests:
  extends: .comparison_tests

  needs:
    - !reference [.comparison_tests, needs]
    - job: prepare_postgrest_hafah_image
      artifacts: true

  variables:
    APP_IMAGE: $HAFAH_IMAGE_NAME

.benchmark_tests:
  extends: .jmeter_benchmark_with_haf_job
  stage: test
  variables:
    FF_NETWORK_PER_BUILD: 1
    API_FOR_TESTING: "account_history_api" # alternatively: blocks_api
    PYTHONPATH: "$CI_PROJECT_DIR/tests/test-tools/package"
    APP_IMAGE: ""
  needs:
    - job: prepare_haf_image
      artifacts: true

  script:
      - /usr/bin/python3 $CI_PROJECT_DIR/tests/tests_api/benchmarks/benchmark.py -a app -p $APP_PORT -c perf_5M_heavy.csv -d $CI_PROJECT_DIR/wdir -n $API_FOR_TESTING
      - m2u --input wdir/raw_jmeter_report.xml --output wdir/jmeter_junit_report.xml
      - jmeter -g wdir/jmeter_${APP_PORT}_output.csv -o wdir/dashboard/
  artifacts:
    paths:
      - wdir/
    reports:
      junit: wdir/jmeter_junit_report.xml
  tags:
    - public-runner-docker
    - hived-for-tests

python_account_history_benchmark_tests:
  extends: .benchmark_tests

  needs:
    - !reference [.benchmark_tests, needs]
    - job: prepare_python_hafah_image
      artifacts: true

  variables:
    APP_IMAGE: $HAFAH_IMAGE_NAME

postgrest_block_api_benchmark_tests:
  extends: .benchmark_tests

  needs:
    - !reference [.benchmark_tests, needs]
    - job: prepare_postgrest_hafah_image
      artifacts: true

  variables:
    APP_IMAGE: $HAFAH_IMAGE_NAME
    API_FOR_TESTING: blocks_api

postgrest_account_history_benchmark_tests:
  extends: .benchmark_tests

  needs:
    - !reference [.benchmark_tests, needs]
    - job: prepare_postgrest_hafah_image
      artifacts: true

  variables:
    APP_IMAGE: $HAFAH_IMAGE_NAME

build_and_publish_image:
  stage: publish
  extends: .publish_docker_image_template
  script:
    - scripts/ci-helpers/build_and_publish_instance.sh
  tags:
    - public-runner-docker