---
test_name: Hivemind database_api.list_comments patterns test order "by_author_last_update" correct paremeters but with wierd post - blank cateogory

marks:
  - patterntest # incomparable with original (bug in fat node using wrong index)

includes:
  - !include ../../../common.yaml

stages:
  - name: list_comments_by_author_last_update
    request:
      url: "{service.proto:s}://{service.server:s}:{service.port}/"
      method: POST
      headers:
        content-type: application/json
      json:
        jsonrpc: "2.0"
        id: 1
        method: "database_api.list_comments"
        params:
          {
            "start": ["xeroc","2016-04-13T16:27:06","xeroc", "how-to-monitor-an-account-on-steem"],
            "limit": 10,
            "order": "by_author_last_update",
          }
    response:
      status_code: 200
      verify_response_with:
        function: validate_response:compare_response_with_pattern
        extra_kwargs:
          method: "all_params_blank_category"
          directory: "database_api_patterns/list_comments/by_author_last_update"

