---
test_name: Hivemind database_api.find_votes all data

marks:
  - patterntest

includes:
  - !include ../../common.yaml

stages:
  - name: database_api.find_votes all data
    request:
      url: "{service.proto:s}://{service.server:s}:{service.port}/"
      method: POST
      headers:
        $ext:
            function: validate_response:get_headers
      json:
        jsonrpc: "2.0"
        id: 1
        method: "database_api.find_votes"
        params:
          {
            "author": "kental",
            "permlink": "hi-steem-my-russian-trip-on-the-bike-big-party-in-moscow-tour-of-moscow-by-slava"
          }
    response:
      status_code: 200
      verify_response_with:
        function: validate_response:compare_response_with_pattern
        extra_kwargs:
          method: "all_data"
          directory: "database_api_patterns/find_votes"