---
test_name: Hivemind database_api.list_comments patterns test order "by_permlink" too many arguments

marks:
  - patterntest
  - negative

includes:
  - !include ../../../common.yaml

stages:
  - name: list_comments by_permlink too many arguments
    request:
      url: "{service.proto:s}://{service.server:s}:{service.port}/"
      method: POST
      headers:
        content-type: application/json
      json:
        jsonrpc: "2.0"
        id: 1
        method: "database_api.list_comments"
        params:
          {
            "start": ["gtg", "hello-world", ""],
            "limit": 10,
            "order": "by_permlink",
          }
    response:
      status_code: 200
      verify_response_with:
        function: validate_response:compare_response_with_pattern
        extra_kwargs:
          method: "too_many_arguments"
          directory: "database_api_negative/list_comments/by_permlink"
          error_response: true