---
test_name: Hivemind database_api.list_votes patterns test order "by_voter_comment"

marks:
  - patterntest

includes:
  - !include ../../../common.yaml

stages:
  - name: list_votes_by_voter_comment
    request:
      url: "{service.proto:s}://{service.server:s}:{service.port}/"
      method: POST
      headers:
        $ext:
            function: validate_response:get_headers
      json:
        jsonrpc: "2.0"
        id: 1
        method: "database_api.list_votes"
        params:
          {
            "start":["boy", "dantheman", "re-sean-king-sexual-click-bait-20160803t200523599z"],
            "limit": 1000,
            "order": "by_voter_comment",
          }
    response:
      status_code: 200
      verify_response_with:
        function: validate_response:compare_response_with_pattern
        extra_kwargs:
          method: "max_limit_page_4"
          directory: "database_api_patterns/list_votes/by_voter_comment"
