---
test_name: Hivemind database_api.list_comments patterns test order "by_cashout_time" invalid date format 2

marks:
  - patterntest
  - negative
includes:
  - !include ../../../common.yaml

stages:
  - name: list_comments_by_cashout_time invalid date format 2
    request:
      url: "{service.proto:s}://{service.server:s}:{service.port}/"
      method: POST
      headers:
        $ext:
            function: validate_response:get_headers
      json:
        jsonrpc: "2.0"
        id: 1
        method: "database_api.list_comments"
        params:
          {
            "start": ["11-08-2016 17:15:12", "", ""],
            "limit": 10,
            "order": "by_cashout_time",
          }
    response:
      status_code: 200
      verify_response_with:
        function: validate_response:compare_response_with_pattern
        extra_kwargs:
          method: "invalid_date_format_2"
          directory: "database_api_negative/list_comments/by_cashout_time"
          error_response: true