---
test_name: Hivemind database_api.find_comments all data

marks:
  - patterntest

includes:
  - !include ../../common.yaml

stages:
  - name: database_api.find_comments all data
    request:
      url: "{service.proto:s}://{service.server:s}:{service.port}/"
      method: POST
      headers:
        content-type: application/json
      json:
        jsonrpc: "2.0"
        id: 1
        method: "database_api.find_comments"
        params:
          {
            "comments": [["magicmonk","hello-steemit-my-name-s-eddie-a-k-a-the-magic-monk-i-am-a-youtuber-and-a-high-school-teacher-let-the-writing-begin"]]
          }
    response:
      status_code: 200
      verify_response_with:
        function: validate_response:compare_response_with_pattern
        extra_kwargs:
          method: "all_data"
          directory: "database_api_patterns/find_comments"
