---
test_name: Hivemind database_api.find_comments all data but specific posts - with blank category (undefined)

marks:
  - patterntest

includes:
  - !include ../../common.yaml

stages:
  - name: database_api.find_comments all data
    request:
      url: "{service.proto:s}://{service.server:s}:{service.port}/"
      method: POST
      headers:
        content-type: application/json
      json:
        jsonrpc: "2.0"
        id: 1
        method: "database_api.find_comments"
        params:
          {
            "comments": [["xeroc","steem-api"], ["xeroc", "how-to-monitor-an-account-on-steem"]]
          }
    response:
      status_code: 200
      verify_response_with:
        function: validate_response:compare_response_with_pattern
        extra_kwargs:
          method: "blank_category"
          directory: "database_api_patterns/find_comments"
