---
test_name: Hivemind database_api.list_comments patterns test order "by_permlink" specific post with blank category

marks:
  - patterntest

includes:
  - !include ../../../common.yaml

stages:
  - name: list_comments_by_permlink
    request:
      url: "{service.proto:s}://{service.server:s}:{service.port}/"
      method: POST
      headers:
        content-type: application/json
      json:
        jsonrpc: "2.0"
        id: 1
        method: "database_api.list_comments"
        params:
          {
            "start": ["xeroc", "steem-api"],
            "limit": 10,
            "order": "by_permlink",
          }
    response:
      status_code: 200
      verify_response_with:
        function: validate_response:compare_response_with_pattern
        extra_kwargs:
          method: "blank_category"
          directory: "database_api_patterns/list_comments/by_permlink"
